### PR TITLE
Windows on ARM64 Build

### PR DESCRIPTION
**Pull request by hmartinez82**
### Add ARM64 configuration and #ifdefs

Note:
- Visual Studio requires the `C++ ARM64 build tools (latest)` component installed
- The `ref_vk` project is disabled in the ARM64 Configuration since there is no Vulkan SDK support  for Windows ARM64, hopefully just yet.
- Binaries are suffixed with `A64`
- The device needs the freely available [OpenCL™ and OpenGL® Compatibility Pack](https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF) provided by Microsoft itself in the Microsoft Store installed 

image

### CODE REVIEW

**Comment by hmartinez82** [comment]
I noticed that my changes broken the OutputDir of some projects. Looking into it now.

**Comment by kondrak** [comment]
I will close this PR now, since it's been over a year since last activity.

**Comment by hmartinez82** [comment]
Yes, sorry. I think I forgot to click the big green Comment button last time. 
Since this project is specifically about Vulkan, it makes no sense my PR which addresses Windows on ARM, by among other things, disabling Vulkan support.

**Comment by hmartinez82** [comment]
@kondrak Good news! There's an official Vulkan SDK for Windows on ARM64 now. I'm testing a local build and will create a new PR soon. I hope it will become a simple just clone and build the .sln file like it is for x64 🚀

**Pull request closed without merging**
