### PR TITLE
added 1920x1200

### PR DESCRIPTION
**Pull request by nonetrix**

### CODE REVIEW

**Comment by nonetrix** [comment]
this check seems to failed due to a error not related to my commit?! sorry this is my first commit

The command "eval git fetch origin +refs/pull/123/merge: " failed 3 times.
The command "git fetch origin +refs/pull/123/merge:" failed and exited with 128 during .
Your build has been stopped.

**Comment by nonetrix** [comment]
if you do merge this please give me a heads up when you make a new release to remind me to update since I'm too lazy to do one console command

**Comment by nonetrix** [comment]
it seems resolutions for Linux are in a completely different folder fun

https://www.youtube.com/watch?v=CXdvwqRhku0

**Comment by nonetrix** [comment]
simple fix now for mac os

**Comment by nonetrix** [comment]
that should do it!

**Comment by nonetrix** [comment]
wait how tf does Vulkan run on mac os? just wondering I thought they pretty much where like nope use our metal cringe API yeet

**Comment by nonetrix** [comment]
I am very professional with words like "yeet" if you couldn't tell

**Comment by nonetrix** [comment]
oh so now the checks pass weird

**Comment by kondrak** [comment]
I cleaned this up a bit and made a separate commit. Thanks for your input!

**Pull request closed without merging**
